# Generated by Django 3.2.18 on 2023-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descriptions',
            field=models.TextField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='descriptions',
            field=models.TextField(),
        ),
    ]
